dataset : {
  shapenet : { _base_: data/ShapeNet-55.yaml,
            others: {subset: 'train','bs': 2}},
  mn40 : { _base_: data/ModelNet40_img_pcl.yaml,
            others: {subset: 'test','bs': 64}}}
            
optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0005,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs : 10
}}

model : {
  NAME: Point_BERT,
  m: 0.999,
  T: 0.07,
  K: 16384,
  transformer_config: {
    mask_ratio: [ 0.4, 0.6 ],
    trans_dim: 384,
    depth: 12,
    drop_path_rate: 0.1,
    cls_dim: 512,
    replace_pob: 0.,
    num_heads: 6,
    moco_loss: False,
    dvae_loss: False,
    cutmix_loss: False,
    return_all_tokens: False,
  },
  dvae_config : {
    group_size: 64,
    num_group: 32,
    encoder_dims: 256,
    num_tokens: 8192,
    tokens_dims: 256,
    decoder_dims: 256,
    ckpt: './checkpoints/dVAE.pth'
  }
}

total_bs : 64
step_per_update : 1
epochs : 300
grad_norm_clip : 10

input_size : 224
mask_patch_size: 32
model_patch_size: 16
model_ema_decay_init: 0.999
warm_it: 200

mask_ratio: 0.5
w_align_image: 0.2
w_fair_image: 1
w_align_pc: 0.2
w_fair_pc: 1
conf_threshold_image: 0.7
conf_threshold_pc: 0.7

lr: 0.0005
warmup_epochs : 2
warmup_steps : 100
eval_freq: 1
npoints: 8192
batch_size : 64
consider_metric: CDL1
from_scratch: True
ulip : True